// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Llh3XvCxgrbPcARVEcC62UXkhSnXsCo',
    appId: '1:74564800563:web:8fd59decd8f2e1d10fd346',
    messagingSenderId: '74564800563',
    projectId: 'fir-flutter-codelab-b156f',
    authDomain: 'fir-flutter-codelab-b156f.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b156f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ktyVoRF6rJgpJJb4YWalOQ96ijprC3E',
    appId: '1:74564800563:android:193a5c25ad323b100fd346',
    messagingSenderId: '74564800563',
    projectId: 'fir-flutter-codelab-b156f',
    storageBucket: 'fir-flutter-codelab-b156f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD9MJQacFs0PbNIgg4RSKm4DTQAFY0YXk',
    appId: '1:74564800563:ios:b29701a87dbe4ee90fd346',
    messagingSenderId: '74564800563',
    projectId: 'fir-flutter-codelab-b156f',
    storageBucket: 'fir-flutter-codelab-b156f.appspot.com',
    iosClientId: '74564800563-j6oc5977v745pdvo89co6m87ppdguqo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD9MJQacFs0PbNIgg4RSKm4DTQAFY0YXk',
    appId: '1:74564800563:ios:b29701a87dbe4ee90fd346',
    messagingSenderId: '74564800563',
    projectId: 'fir-flutter-codelab-b156f',
    storageBucket: 'fir-flutter-codelab-b156f.appspot.com',
    iosClientId: '74564800563-j6oc5977v745pdvo89co6m87ppdguqo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
